import type { Metadata } from "next";
import "../../public/scss/main.scss";
import Provider from "@/state/provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Provider>
      <html lang="en" className="">
        <body>{children}</body>
      </html>
    </Provider>
  );
}
